# Name: Yash Meshram

# Assignment-3 : question-3, 4, 5 and 6

# question-3

In [ ]:
import math
import numpy as np

def deg(theta):
    rad = (math.pi/180)*theta
    return rad

def cos(q):
    return math.cos(deg(q))

def sin(q):
    return math.sin(deg(q))

In [ ]:
def R_(ap, teta):
    R = np.array([[cos(teta), -sin(teta)*cos(ap),  sin(teta)*sin(ap)],
                  [sin(teta),  cos(teta)*cos(ap), -cos(teta)*sin(ap)],
                  [        0,            sin(ap),            cos(ap)]])
    return R
def P_(a, d, teta):
    P = np.array([[a*cos(teta)],
                  [a*sin(teta)],
                  [d]])
    return P

def solve(n, s, DH):
    To = np.identity(4, dtype = float)
    extra_row = np.array([0, 0, 0, 1])

    for i in range(n):
        a_i = DH[i][0]
        ap_i = DH[i][1]
        d_i = DH[i][2]
        teta_i = DH[i][3]

        R_i = R_(ap_i, teta_i)
        P_i = P_(a_i, d_i, teta_i)
        A_i = np.vstack((np.concatenate((R_i, P_i), axis=1), extra_row))
        To = np.dot(To, A_i)

    Pn = np.array([[To[0][3]],
                [To[1][3]],
                [To[2][3]]])


    T = np.identity(4, dtype = float)
    z = np.array([[0],
                [0],
                [1]])
    Pn = np.transpose(Pn)

    J = np.zeros([6,1])
    if s[0] == 'R':
        J0 = np.concatenate((np.cross(np.transpose(z), Pn), np.transpose(z)), axis=1)
    elif s[0] == 'P':
        J0 = np.concatenate((np.transpose(z), np.zeros([1,3])), axis=1)
    J = np.concatenate((J, np.transpose(J0)), axis=1)
    J = np.delete(J, 0, axis=1)

    for i in range(n-1):
        a_i = DH[i][0]
        ap_i = DH[i][1]
        d_i = DH[i][2]
        teta_i = DH[i][3]

        R_i = R_(ap_i, teta_i)
        P_i = P_(a_i, d_i, teta_i)
        A_i = np.vstack((np.concatenate((R_i, P_i), axis=1), extra_row))
        T = np.dot(T, A_i)
        R = T[:3,:3]
        P = np.transpose(T[:3,3])

        Z_i = np.transpose(np.dot(R, z))
        if s[i+1] == 'R':
            r1 = np.cross(Z_i, (Pn - P))
            r2 = Z_i
        elif s[i+1] == 'P':
            r1 = Z_i
            r2 = np.zeros([1,3])
        Ji = np.concatenate((r1, r2), axis = 1)
        Ji = np.transpose(Ji)
        J = np.concatenate((J, Ji), axis = 1)
    Pn = np.transpose(Pn)

    W = np.array([0])
    for i in range(n):
        if s[i] == 'R':
            W = np.append(W, [5])
        elif s[i] == 'P':
            W = np.append(W, [0])
    W = np.delete(W, [0])

    print('(a) Complete manipulator Jacobian = \n', J)
    print('\n')
    print('(b) End-effector position = \n', Pn)
    print('\n')
    print('(c) End-effector velocity = \n', np.dot(J, np.transpose(W)))
    print('\n')
    print('T = \n', To)

In [ ]:
# Inputs
n = 3                                     # Number of links
s = 'RRR'                                 # Type of joints
DH = np.array([[10, 0, 0, 45],            # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i])
               [10, 0, 0, 90],           
               [10, 0, 0, 45]])

# Calculating
solve(n, s, DH)

(a) Complete manipulator Jacobian = 
 [[-1.41421356e+01 -7.07106781e+00 -1.77635684e-15]
 [-1.00000000e+01 -1.70710678e+01 -1.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00]]


(b) End-effector position = 
 [[-10.        ]
 [ 14.14213562]
 [  0.        ]]


(c) End-effector velocity = 
 [-106.06601718 -185.35533906    0.            0.            0.
   15.        ]


T = 
 [[-1.00000000e+00 -1.79380389e-16  0.00000000e+00 -1.00000000e+01]
 [ 1.99673462e-16 -1.00000000e+00  0.00000000e+00  1.41421356e+01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# question-4:
# RRP - SCARA

In [ ]:
# Inputs
n = 3                                      # Number of links
s = 'RRP'
DH = np.array([[10,   0, 0, 30],           # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i]) 
               [10, 180, 0, 45],           
               [0,    0, 5, 0]])

# Calculating
solve(n, s, DH)

(a) Complete manipulator Jacobian = 
 [[-1.46592583e+01 -9.65925826e+00  1.18291797e-16]
 [ 1.12484445e+01  2.58819045e+00 -3.16961915e-17]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  0.00000000e+00]]


(b) End-effector position = 
 [[11.24844449]
 [14.65925826]
 [-5.        ]]


(c) End-effector velocity = 
 [-121.59258263   69.1831747     0.            0.            0.
   10.        ]


T = 
 [[ 2.58819045e-01  9.65925826e-01  1.18291797e-16  1.12484445e+01]
 [ 9.65925826e-01 -2.58819045e-01 -3.16961915e-17  1.46592583e+01]
 [ 0.00000000e+00  1.22464680e-16 -1.00000000e+00 -5.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# question-4:
# RRP - standford

In [ ]:
# Inputs
n = 3                                      # Number of links
s = 'RRP'
DH = np.array([[ 0, 90, 10, 30],           # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i]) 
               [10,  0,  0, 45],           
               [ 5,  0,  0, 0]])

# Calculating
solve(n, s, DH)

(a) Complete manipulator Jacobian = 
 [[-5.30330086e+00 -9.18558654e+00  5.00000000e-01]
 [ 9.18558654e+00 -5.30330086e+00 -8.66025404e-01]
 [ 0.00000000e+00  1.06066017e+01  6.12323400e-17]
 [ 0.00000000e+00  5.00000000e-01  0.00000000e+00]
 [ 0.00000000e+00 -8.66025404e-01  0.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00]]


(b) End-effector position = 
 [[ 9.18558654]
 [ 5.30330086]
 [20.60660172]]


(c) End-effector velocity = 
 [-72.44443697  19.41142838  53.03300859   2.5         -4.33012702
   5.        ]


T = 
 [[ 6.12372436e-01 -6.12372436e-01  5.00000000e-01  9.18558654e+00]
 [ 3.53553391e-01 -3.53553391e-01 -8.66025404e-01  5.30330086e+00]
 [ 7.07106781e-01  7.07106781e-01  6.12323400e-17  2.06066017e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# question-5: for PPP




In [ ]:
# Inputs
n = 3                                       # Number of links
s = 'PPP'                                   # Type of joints
DH = np.array([[0, -90, 2,   0],            # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i])
               [0, -90, 3, -90],           
               [0,   0, 5,   0]])

# calculating
solve(n, s, DH)

(a) Complete manipulator Jacobian = 
 [[ 0.000000e+00  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17]
 [ 1.000000e+00  6.123234e-17 -6.123234e-17]
 [ 0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00]]


(b) End-effector position = 
 [[5.]
 [3.]
 [2.]]


(c) End-effector velocity = 
 [0. 0. 0. 0. 0. 0.]


T = 
 [[ 6.123234e-17  6.123234e-17  1.000000e+00  5.000000e+00]
 [-6.123234e-17 -1.000000e+00  6.123234e-17  3.000000e+00]
 [ 1.000000e+00 -6.123234e-17 -6.123234e-17  2.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]


# question-6

In [ ]:
# Inputs
n = 6                                       # Number of links
s = 'RRRRRR'                                # Type of joints
DH = np.array([[ 0, 90, 0,  0],            # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i])
               [ 1,  0, 0,  0],           
               [ 1,  0, 0,  0],
               [ 0,-90, 0,  0],
               [ 0,-90, 0,-90],
               [ 0,  0, 1,  0]])

# calculating
solve(n, s, DH)

(a) Complete manipulator Jacobian = 
 [[-6.1232340e-17 -6.1232340e-17 -6.1232340e-17 -6.1232340e-17
  -6.1232340e-17  0.0000000e+00]
 [ 3.0000000e+00  1.8369702e-16  1.2246468e-16  6.1232340e-17
   1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  3.0000000e+00  2.0000000e+00  1.0000000e+00
   0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  1.0000000e+00]
 [ 0.0000000e+00 -1.0000000e+00 -1.0000000e+00 -1.0000000e+00
   0.0000000e+00  6.1232340e-17]
 [ 1.0000000e+00  6.1232340e-17  6.1232340e-17  6.1232340e-17
   1.0000000e+00  6.1232340e-17]]


(b) End-effector position = 
 [[3.000000e+00]
 [6.123234e-17]
 [6.123234e-17]]


(c) End-effector velocity = 
 [-1.5308085e-15  2.0000000e+01  3.0000000e+01  5.0000000e+00
 -1.5000000e+01  1.0000000e+01]


T = 
 [[ 6.12323400e-17  6.12323400e-17  1.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  3.74939946e-33  6.12323400e-17  6.12323400e-17]
 [ 0.00000000e+00 -1.00000000e+00  6.123234