Question-7: RRP Scara
(Note: For downward translation of prismatic join insert a negative value of d and vice-a-versa)

In [1]:
import numpy as np

l1=int(input("l1="))
l2=int(input("l2="))
q1=int(input("q1(degree)="))
q2=int(input("q2(degree)="))
d=int(input("d="))

q1=q1*(np.pi)/180
q2=q2*(np.pi)/180
x = l1*np.cos(q1) + l2*np.cos(q1+q2)
y = l1*np.sin(q1) + l2*np.sin(q1+q2)
z = d

print("(x,y,z) = (",x,",",y,",",z,")")


l1=5
l2=10
q1(degree)=90
q2(degree)=90
d=-5
(x,y,z) = ( -10.0 , 5.000000000000001 , -5 )


Question-8:RRP stanford

In [2]:
import numpy as np

l1=int(input("l1="))
l2=int(input("l2="))
q1=int(input("q1(degree)="))
q2=int(input("q2(degree)="))
d=int(input("d="))

q1=q1*(np.pi)/180
q2=q2*(np.pi)/180
x = (l2+d)*np.cos(q1)*np.cos(q2)
y = (l2+d)*np.sin(q1)*np.cos(q2)
z = (l2+d)*np.sin(q2)+l1

print("(x,y,z) = (",x,",",y,",",z,")")


l1=10
l2=5
q1(degree)=90
q2(degree)=0
d=10
(x,y,z) = ( 9.18485099360515e-16 , 15.0 , 10.0 )


Question-12: RRP scara jacobian
(Note: For downward translation of prismatic join insert a negative value of d and vice-a-versa)

In [6]:
import numpy as np

l1=int(input("l1="))
l2=int(input("l2="))
q1=int(input("q1(degree)="))
q2=int(input("q2(degree)="))
d=int(input("d="))

q1=q1*(np.pi)/180
q2=q2*(np.pi)/180

R1 = [(-l1*np.sin(q1)-l2*np.sin(q1+q2)), (-l2*np.sin(q1+q2)), 0] 
R2 = [(l1*np.cos(q1)+l2*np.cos(q1+q2)), l2*np.cos(q1+q2), 0]
R3 = [0, 0 , 1]
R4 = [0, 0, 0]
R5 = [0, 0, 0]
R6 = [1, 1, 0]
J =[R1, R2, R3, R4, R5, R6]
print("Jacobian Matrix =\n", np.array(J))


l1=10
l2=15
q1(degree)=45
q2(degree)=30
d=-10
Jacobian Matrix =
 [[-21.55995521 -14.48888739   0.        ]
 [ 10.95335349   3.88228568   0.        ]
 [  0.           0.           1.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  1.           1.           0.        ]]


Question-14:RRR planar jacobian

In [5]:
import numpy as np

l1=int(input("l1="))
l2=int(input("l2="))
l3=int(input("l3="))
q1=int(input("q1(degree)="))
q2=int(input("q2(degree)="))
q3=int(input("q3(degree)="))

q1=q1*(np.pi)/180
q2=q2*(np.pi)/180
q3=q3*(np.pi)/180

R1 = [(-l1*np.sin(q1)-l2*np.sin(q1+q2)-l3*np.sin(q1+q2+q3)), (-l2*np.sin(q1+q2)-l3*np.sin(q1+q2+q3)), (-l3*np.sin(q1+q2+q3))] 
R2 = [(l1*np.cos(q1)+l2*np.cos(q1+q2)+l3*np.cos(q1+q2+q3)), (l2*np.cos(q1+q2)+l3*np.cos(q1+q2+q3)), (l3*np.cos(q1+q2+q3))]
R3 = [0, 0 , 0]
R4 = [0, 0, 0]
R5 = [0, 0, 0]
R6 = [1, 1, 1]
J =[R1, R2, R3, R4, R5, R6]

print("Jacobian Matrix =\n", np.array(J))


l1=5
l2=10
l3=5
q1(degree)=90
q2(degree)=0
q3(degree)=0
Jacobian Matrix =
 [[-2.00000000e+01 -1.50000000e+01 -5.00000000e+00]
 [ 1.22464680e-15  9.18485099e-16  3.06161700e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00]]
