# Name: Yash Meshram

# Assignment-4

# question 1

In [ ]:
import math
import numpy as np

def deg(theta):
    rad = (math.pi/180)*theta
    return rad

def cos(q):
    return math.cos(deg(q))

def sin(q):
    return math.sin(deg(q))

def atan(q1, q2):
    return (180/math.pi)*math.atan(q1/q2)

In [ ]:
# Input
P = [10, 15, 12]       # P = [px, py, pz]
l1 = 5               # link 1 length
l2 = 10              # link 2 length

In [ ]:
def question1(P, l1, l2):
    (px, py, pz) = (P[0], P[1], P[2])

    theta1 = atan(py, px)
    r = math.sqrt(px**2 + py**2)
    s = pz - l1
    theta2 = atan(s, r)
    d3 = math.sqrt(r**2 + s**2) - l2

    print('\u03B81 = {}\u00B0'.format(round(theta1, 2)))
    print('\u03B82 = {}\u00B0'.format(round(theta2, 2)))
    print('d3 = {}'.format(round(d3, 2)))

question1(P, l1, l2)

θ1 = 56.31°
θ2 = 21.22°
d3 = 9.34


# question 2

In [ ]:
# Input
a = 60                                              # consider theta4=0 then a = theta1 + theta2
T = np.array([[cos(a),  sin(a),      0,      3],
              [sin(a), -cos(a),      0,      5],
              [     0,       0,      1,      7],
              [     0,       0,      0,      1]])
a1 = 3
a2 = 3
d4 = 6

In [ ]:
def question2(T, a1, a2, d4):
    R = T[:3,:3]
    d = T[:3,3]
    (r11, r12) = (R[0,0], R[0,1])
    (dx, dy, dz) = (d[0], d[1], d[2])

    a = atan(r12, r11)
    r = (dx**2 + dy**2 - a1**2 - a2**2)/(2*a1*a2)
    theta2 = atan(np.sqrt(1 - r**2), r)
    # theta1 = atan(dx, dy) - atan(a1 + a2*cos(theta2), a2*sin(theta2))
    # theta4 = theta1 + theta2 - a
    d3 = dz - d4
    theta1 = atan(dy, dx) - atan(a2*sin(theta2),(a1 + a2*cos(theta2)))

    print('\u03B81 = {}\u00B0'.format(round(theta1, 2)))
    print('\u03B82 = {}\u00B0'.format(round(theta2, 2)))
    print('d3 = {}'.format(round(d3, 2)))

question2(T, a1, a2, d4)

θ1 = 45.4°
θ2 = 27.27°
d3 = 1.0


# question 3

In [ ]:
# Inputs
n = 3                                     # Number of links
s = 'RRR'                                 # Type of joints
DH = np.array([[10, 0, 0, 45],            # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i])
               [10, 0, 0, 90],           
               [10, 0, 0, 45]])
X_dot = np.array([[4], [5], [9], [1], [2], [3]])

In [ ]:
def R_(ap, teta):
    R = np.array([[cos(teta), -sin(teta)*cos(ap),  sin(teta)*sin(ap)],
                  [sin(teta),  cos(teta)*cos(ap), -cos(teta)*sin(ap)],
                  [        0,            sin(ap),            cos(ap)]])
    return R
def P_(a, d, teta):
    P = np.array([[a*cos(teta)],
                  [a*sin(teta)],
                  [d]])
    return P

def question3(n, s, DH, X_dot):
    To = np.identity(4, dtype = float)
    extra_row = np.array([0, 0, 0, 1])

    for i in range(n):
        a_i = DH[i][0]
        ap_i = DH[i][1]
        d_i = DH[i][2]
        teta_i = DH[i][3]

        R_i = R_(ap_i, teta_i)
        P_i = P_(a_i, d_i, teta_i)
        A_i = np.vstack((np.concatenate((R_i, P_i), axis=1), extra_row))
        To = np.dot(To, A_i)

    Pn = np.array([[To[0][3]],
                [To[1][3]],
                [To[2][3]]])


    T = np.identity(4, dtype = float)
    z = np.array([[0],
                [0],
                [1]])
    Pn = np.transpose(Pn)

    J = np.zeros([6,1])
    if s[0] == 'R':
        J0 = np.concatenate((np.cross(np.transpose(z), Pn), np.transpose(z)), axis=1)
    elif s[0] == 'P':
        J0 = np.concatenate((np.transpose(z), np.zeros([1,3])), axis=1)
    J = np.concatenate((J, np.transpose(J0)), axis=1)
    J = np.delete(J, 0, axis=1)

    for i in range(n-1):
        a_i = DH[i][0]
        ap_i = DH[i][1]
        d_i = DH[i][2]
        teta_i = DH[i][3]

        R_i = R_(ap_i, teta_i)
        P_i = P_(a_i, d_i, teta_i)
        A_i = np.vstack((np.concatenate((R_i, P_i), axis=1), extra_row))
        T = np.dot(T, A_i)
        R = T[:3,:3]
        P = np.transpose(T[:3,3])

        Z_i = np.transpose(np.dot(R, z))
        if s[i+1] == 'R':
            r1 = np.cross(Z_i, (Pn - P))
            r2 = Z_i
        elif s[i+1] == 'P':
            r1 = Z_i
            r2 = np.zeros([1,3])
        Ji = np.concatenate((r1, r2), axis = 1)
        Ji = np.transpose(Ji)
        J = np.concatenate((J, Ji), axis = 1)

    J_inv = np.linalg.pinv(J)
    q_dot = np.dot(J_inv, X_dot)
    print('q\u0307 =')
    print(q_dot)

question3(n, s, DH, X_dot)

q̇ =
[[ 2.19203102]
 [-4.94974747]
 [ 5.75771645]]


# question 6

In [ ]:
# Input
R = np.array([[.1, .2, .3],
              [.4, .5, .6],
              [.7, .8, .9]])

In [ ]:
(u13, u23, u33, u31, u32) = (R[0,2], R[1,2], R[2,2], R[2,0], R[2,1])

theta = atan(np.sqrt(1-u33**2), u33)
phi = atan(u23, u13)
psi = atan(u32, -u31)

print('\u03B8 = {}\u00B0'.format(theta))
print('\u03A6 = {}\u00B0'.format(phi))
print('\u03A8 = {}\u00B0'.format(psi))

θ = 25.841932763167126°
Φ = 63.43494882292201°
Ψ = -48.81407483429036°


# question 7

In [ ]:
def R_(ap, teta):
    R = np.array([[cos(teta), -sin(teta)*cos(ap),  sin(teta)*sin(ap)],
                  [sin(teta),  cos(teta)*cos(ap), -cos(teta)*sin(ap)],
                  [        0,            sin(ap),            cos(ap)]])
    return R
def P_(a, d, teta):
    P = np.array([[a*cos(teta)],
                  [a*sin(teta)],
                  [d]])
    return P

def question7(n, s, DH):
    To = np.identity(4, dtype = float)
    extra_row = np.array([0, 0, 0, 1])

    for i in range(n):
        a_i = DH[i][0]
        ap_i = DH[i][1]
        d_i = DH[i][2]
        teta_i = DH[i][3]

        R_i = R_(ap_i, teta_i)
        P_i = P_(a_i, d_i, teta_i)
        A_i = np.vstack((np.concatenate((R_i, P_i), axis=1), extra_row))
        To = np.dot(To, A_i)

    Pn = np.array([[To[0][3]],
                [To[1][3]],
                [To[2][3]]])


    T = np.identity(4, dtype = float)
    z = np.array([[0],
                [0],
                [1]])
    Pn = np.transpose(Pn)

    J = np.zeros([6,1])
    if s[0] == 'R':
        J0 = np.concatenate((np.cross(np.transpose(z), Pn), np.transpose(z)), axis=1)
    elif s[0] == 'P':
        J0 = np.concatenate((np.transpose(z), np.zeros([1,3])), axis=1)
    J = np.concatenate((J, np.transpose(J0)), axis=1)
    J = np.delete(J, 0, axis=1)

    for i in range(n-1):
        a_i = DH[i][0]
        ap_i = DH[i][1]
        d_i = DH[i][2]
        teta_i = DH[i][3]

        R_i = R_(ap_i, teta_i)
        P_i = P_(a_i, d_i, teta_i)
        A_i = np.vstack((np.concatenate((R_i, P_i), axis=1), extra_row))
        T = np.dot(T, A_i)
        R = T[:3,:3]
        P = np.transpose(T[:3,3])

        Z_i = np.transpose(np.dot(R, z))
        if s[i+1] == 'R':
            r1 = np.cross(Z_i, (Pn - P))
            r2 = Z_i
        elif s[i+1] == 'P':
            r1 = Z_i
            r2 = np.zeros([1,3])
        Ji = np.concatenate((r1, r2), axis = 1)
        Ji = np.transpose(Ji)
        J = np.concatenate((J, Ji), axis = 1)
    Pn = np.transpose(Pn)

    W = np.array([0])
    for i in range(n):
        if s[i] == 'R':
            W = np.append(W, [5])
        elif s[i] == 'P':
            W = np.append(W, [1])
    W = np.delete(W, [0])

    print('End-effector position = \n', Pn)
    print('\n')
    print('End-effector velocity = \n', np.dot(J, np.transpose(W)))

In [ ]:
# Inputs
n = 3                                       # Number of links
s = 'PPP'                                   # Type of joints
DH = np.array([[0, -90, 2,   0],            # DH Parameters (EACH ROW IN ORDER [ai, alpha_i, di, theta_i])
               [0, -90, 3, -90],           
               [0,   0, 5,   0]])

# calculating
question7(n, s, DH)

End-effector position = 
 [[5.]
 [3.]
 [2.]]


End-effector velocity = 
 [1. 1. 1. 0. 0. 0.]
