In [ ]:
import math
import numpy as np

def deg(theta):
    rad = (math.pi/180)*theta
    return rad

def cos(q):
    return math.cos(deg(q))

def sin(q):
    return math.sin(deg(q))

In [ ]:
# parameters
l1 = 10     # cm
l2 = 10     # cm
l3 = 10     # cm
d = 5       # cm

q1 = 30     # deg.
q2 = 30     # deg.

In [ ]:
extra_row = np.array([0, 0, 0, 1])

R_01 = np.array([[cos(q1), -sin(q1), 0],
                 [sin(q1), cos(q1), 0],
                 [0, 0, 1]])

d_01 = np.array([[0],[0],[l1]])

h_01 = np.concatenate((R_01, d_01), axis=1)
H_01 = np.vstack((h_01, extra_row))

print("R_01 = \n", R_01, "\n")
print("d_01 = \n", d_01, "\n")
print("H_01 = \n", H_01, "\n")

R_01 = 
 [[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]] 

d_01 = 
 [[ 0]
 [ 0]
 [10]] 

H_01 = 
 [[ 0.8660254 -0.5        0.         0.       ]
 [ 0.5        0.8660254  0.         0.       ]
 [ 0.         0.         1.        10.       ]
 [ 0.         0.         0.         1.       ]] 



In [ ]:
R_12 = np.array([[cos(q2), -sin(q2), 0],
                 [sin(q2), cos(q2), 0],
                 [0, 0, 1]])

d_12 = np.array([[l2],[0],[0]])

h_12 = np.concatenate((R_12, d_12), axis=1)
H_12 = np.vstack((h_12, extra_row))

print("R_12 = \n", R_12, "\n")
print("d_12 = \n", d_12, "\n")
print("H_12 = \n", H_12, "\n")

R_12 = 
 [[ 0.8660254 -0.5        0.       ]
 [ 0.5        0.8660254  0.       ]
 [ 0.         0.         1.       ]] 

d_12 = 
 [[10]
 [ 0]
 [ 0]] 

H_12 = 
 [[ 0.8660254 -0.5        0.        10.       ]
 [ 0.5        0.8660254  0.         0.       ]
 [ 0.         0.         1.         0.       ]
 [ 0.         0.         0.         1.       ]] 



In [ ]:
R_23 = np.array([[0, 0, 1],
                 [0, 1, 0],
                 [-1, 0, 0]])

d_23 = np.array([[l3],[0],[0]])

h_23 = np.concatenate((R_23, d_23), axis=1)
H_23 = np.vstack((h_23, extra_row))

print("R_23 = \n", R_23, "\n")
print("d_23 = \n", d_23)
print("H_23 = \n", H_23)

R_23 = 
 [[ 0  0  1]
 [ 0  1  0]
 [-1  0  0]] 

d_23 = 
 [[10]
 [ 0]
 [ 0]]
H_23 = 
 [[ 0  0  1 10]
 [ 0  1  0  0]
 [-1  0  0  0]
 [ 0  0  0  1]]


In [ ]:
P_3 = np.array([[d], [0], [0]])
p_3 = np.append(P_3, [[1]], axis=0)

print("P_3 = \n", P_3)

P_3 = 
 [[5]
 [0]
 [0]]


In [ ]:
# Final Output
H_23__p_3 = np.dot(H_23, p_3)
H_12__H_23_p_3 = np.dot(H_12, H_23__p_3)
H_01__H_12__H_23_p_3 = np.dot(H_01, H_12__H_23_p_3)
p_0 = H_01__H_12__H_23_p_3
P_0 = np.array([[p_0[0][0]],
                [p_0[1][0]],
                [p_0[2][0]]])

print("P_0 = \n",P_0)

P_0 = 
 [[13.66025404]
 [13.66025404]
 [ 5.        ]]
