In [ ]:
import math
import numpy as np

def deg(theta):
    rad = (math.pi/180)*theta
    return rad

def cos(q):
    return math.cos(deg(q))

def sin(q):
    return math.sin(deg(q))

In [ ]:
# Parameters
l1 = 10     # cm
l2 = 10     # cm
d = 5       # cm
h = 0      # cm

q1 = 30     # deg.
q2 = 30     # deg.

In [ ]:
z0 = np.array([[0], [0], [1]])
z1 = np.array([[0], [0], [1]])
z2 = np.array([[0], [0], [-1]])

O0 =np.array([[0], [0], [0]])
O1 =np.array([[l1*cos(q1)], [l2*sin(q1)], [h]])
O2 =np.array([[l1*cos(q1) + l2*cos(q1+q2)], [l2*sin(q1) + l2*sin(q1+q2)], [h]])
O3 =np.array([[l1*cos(q1) + l2*cos(q1+q2)], [l2*sin(q1) + l2*sin(q1+q2)], [h-d]])

zero = np.zeros((3,1), dtype=int)

# A = z0 x (O3 - O0)
# B = z1 x (O3 - O1)

A = np.array([[-l1*sin(q1) - l2*sin(q1+q2)],
              [l1*cos(q1) + l2*cos(q1+q2)],
              [0]])

B = np.array([[-l2*sin(q1+q2)],
              [l2*cos(q1+q2)],
              [0]])

In [ ]:
# Output
Jv = np.concatenate((A, B, z2), axis=1)
print('Jv = \n', Jv, '\n')

Jw = np.concatenate((z0, z1, zero), axis=1)
print('Jw = \n', Jw, '\n')

J = np.concatenate((Jv, Jw))
print('J = \n', J)

Jv = 
 [[-13.66025404  -8.66025404   0.        ]
 [ 13.66025404   5.           0.        ]
 [  0.           0.          -1.        ]] 

Jw = 
 [[0 0 0]
 [0 0 0]
 [1 1 0]] 

J = 
 [[-13.66025404  -8.66025404   0.        ]
 [ 13.66025404   5.           0.        ]
 [  0.           0.          -1.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  1.           1.           0.        ]]
