In [ ]:
import math
import numpy as np

def deg(theta):
    rad = (math.pi/180)*theta
    return rad

def cos(q):
    return math.cos(deg(q))

def sin(q):
    return math.sin(deg(q))

In [ ]:
# Parameters
l1 = 10     # cm
l2 = 10     # cm
l3 = 10     # cm

q1 = 15     # deg.
q2 = 30     # deg.
q3 = 60     # deg.

In [ ]:
z0 = np.array([[0], [0], [1]])
z1 = z0
z2 = z0
z3 = z0

O0 =np.array([[0], [0], [0]])
O1 =np.array([[l1*cos(q1)], [l2*sin(q1)], [0]])
O2 =np.array([[l1*cos(q1) + l2*cos(q2)], [l2*sin(q1) + l2*sin(q2)], [0]])
O3 =np.array([[l1*cos(q1) + l2*cos(q2) + l3*cos(q3)], [l2*sin(q1) + l2*sin(q2) + l3*sin(q3)], [0]])

# A = z0 x (O3 - O0)
# B = z1 x (O3 - O1)
# C = z2 x (O3 - O2)

A = np.array([[-l1*sin(q1) - l2*sin(q2) - l3*sin(q3)],
              [l1*cos(q1) + l2*cos(q2) + l3*cos(q3)],
              [0]])

B = np.array([[-l2*sin(q2) - l3*sin(q3)],
              [l2*cos(q2) + l3*cos(q3)],
              [0]])

C = np.array([[-l3*sin(q3)],
              [l3*cos(q3)],
              [0]])

In [ ]:
# Output
Jv = np.concatenate((A, B, C), axis=1)
print('Jv = \n', Jv, '\n')

Jw = np.concatenate((z0, z1, z2), axis=1)
print('Jw = \n', Jw, '\n')

J = np.concatenate((Jv, Jw))
print('J = \n', J)

Jv = 
 [[-16.24844449 -13.66025404  -8.66025404]
 [ 23.3195123   13.66025404   5.        ]
 [  0.           0.           0.        ]] 

Jw = 
 [[0 0 0]
 [0 0 0]
 [1 1 1]] 

J = 
 [[-16.24844449 -13.66025404  -8.66025404]
 [ 23.3195123   13.66025404   5.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  1.           1.           1.        ]]
